language: node_js
node_js:
  - '4.1'
install:
  - npm install
before_script:
  - chmod +x deploy.sh
script: ./deploy.sh
test: true
branches:
  only:
    - master
env:
  global:
    - secure: wu4mO6ZhGLeZAVX5khHRe+JGFtVlij3QGuTvcxECgdHhzJbKfNqCLcnuFmfwjb+gQmvUesgRO1TleZWch45rs3K6A99zF+FmAyzoeb+ESsS5RqzvOys9IIO2QhY1rbzjpdFdL+/I47HvcI+BCz22mTaaJX1Xu4+HOz4Fxsuxo0/YlSR2esd6LKD57b49ejaBvLuU+dSxoLVxhDZ2XipXfpEBCzcw0J2Z9BmHj2dFTpn56eA/ziYjFg13VEYHglIvPGX0G6Y07Kljs39MhBSog9LF255foz6UoKwg6VNl1ilPxBd5JhlKmpd93LbAavqiTHjrNxopgTlFdfJd5egw0/mRQcaBYPu/ekVxs5gqkriveyJ3rc2VGi1/2ZiRpXLi0HFZFtIGBhcoCtfESaiCdbClNYsjMwWa93Di2FU1ssKkVwgfXGF2fvbVkDKRfR0caNHpe8nMIi/DvTMdXDSUQBKP5DOyFCFAUl1hB+I+/QMfG4GQfKE8TsXOf32Qul8RaYZ+IOOM6nsnb3V1dq+2amVkJ9L2UuMlZfD0aNXwSwUQbqqrk+6YNProtcJ32a6gYFBJ0UdxTD8BkpWUdAPhHxSdU2tXMt4lFWys0R4K6UEAgAWYL0RgohJte318y/xaKW1c/ppA+BkpGIJrntNIRARTsnQb7vbcjZ3D17UGzpk=
